### ISSUE TITLE
We should actually use `rng` in `rand!(rng, sampler)`

### ISSUE THREAD

**Issue by shengjiex98** [Ratfink/RealTimeScheduling.jl#21]
Currently in `Random.rand!(rng, a, sampler)` the argument `rng` is not used instead of the default `Random.rand()`. We should change this. Does `rand(rng)` fix it? Or should we remove this argument all together?

https://github.com/Ratfink/RealTimeScheduling.jl/blob/29b345818136ae53e31520ae106d073f6eedb052/src/weaklyhard.jl#L219-L234

**Comment by Ratfink** [comment]
An oversight on my part!  Yes, it should be changed to `rand(rng)` on line 228.
